name: .NET CI
on: [push]

jobs:
  build:
    
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout Code

        # Install the .NET workload
      - name: Install .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100
        
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.
 
      - name: Build App
        run: dotnet build "LABS Experiences\LABS Experiences\LABS Experiences.csproj" -c Release

      - name: Test App
        run: dotnet test "LABS Experiences\LABS Experiences\LABS Experiences.csproj"
