name: License Check Copyright

on:
  schedule:
    - cron: "0 3 1 1 *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: FantasticFiasco/action-update-license-year@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commitTitle: 'Updated license copyright'
        assignees: 'lpeyr'
        labels: documentation
        path: LICENSE.md
